/**
 * The design-time half of every test, inlined here so the HTML report is
 * self-contained: purpose, what is under test, method (setup + exact inputs),
 * expected result. Keyed by test ID. The report matches Vitest results to these
 * by the ID prefix in each test title.
 *
 * This mirrors qa/specs/*.md — the prose source of record. If you change a test
 * spec, update the matching entry here.
 */

export const GOVERNING = {
  US: { file: "docs/specs/05-user-layers.md", sec: "§4, §10 decision 1", specFile: "qa/specs/unit-userService.md", src: "qa/tests/unit/userService.test.ts" },
  RA: { file: "docs/specs/06-server-modules.md", sec: "§4", specFile: "qa/specs/unit-requireAuth.md", src: "qa/tests/unit/requireAuth.test.ts" },
  EH: { file: "docs/specs/06-server-modules.md", sec: "§3 (+ 03 §0)", specFile: "qa/specs/unit-errorHandling.md", src: "qa/tests/unit/errorHandling.test.ts" },
  LG: { file: "docs/specs/06-server-modules.md", sec: "§1 (+ 01 §9)", specFile: "qa/specs/int-logger.md", src: "qa/tests/integration/logger.test.ts" },
  MD: { file: "docs/specs/04-data-model.md", sec: "User / RefreshToken / Expense", specFile: "qa/specs/int-models.md", src: "qa/tests/integration/models.test.ts" },
  DB: { file: "docs/specs/06-server-modules.md", sec: "§2, §6 decision 3", specFile: "qa/specs/int-db.md", src: "qa/tests/integration/db.test.ts" },
  ST: { file: "docs/specs/07-server-entry.md", sec: "§1 (+ 06 §2)", specFile: "qa/specs/int-startup.md", src: "qa/tests/integration/startup.test.ts" },
  SU: { file: "docs/specs/03-api-contract.md", sec: "§0-§1 (+ 05 §5-§8, §10 d4)", specFile: "qa/specs/api-signup.md", src: "qa/tests/api/01-signup.test.ts" },
  RF: { file: "docs/specs/03-api-contract.md", sec: "§1 (+ 05 §6/§8, 04, 06 §3.3)", specFile: "qa/specs/api-refresh.md", src: "qa/tests/api/02-refresh.test.ts" },
  LO: { file: "docs/specs/03-api-contract.md", sec: "§1 (+ 05 §6)", specFile: "qa/specs/api-logout.md", src: "qa/tests/api/03-logout.test.ts" },
  XC: { file: "docs/specs/03-api-contract.md", sec: "§0 (+ 07 §2/§4, 05 §5, 06 §3)", specFile: "qa/specs/api-crosscutting.md", src: "qa/tests/api/04-crosscutting.test.ts" },
  LI: { file: "docs/specs/03-api-contract.md", sec: "§1 (+ 05 §6-§8)", specFile: "qa/specs/api-login.md", src: "qa/tests/api/05-login.test.ts" },
  UJ: { file: "docs/specs/01-ai-chat.md", sec: "§1, §4 (+ 03 §1, 05 §4/§6)", specFile: "qa/specs/e2e-auth-journey.md", src: "qa/e2e/tests/auth-journey.spec.ts" },
};

export const GROUPS = [
  { key: "US", title: "Unit — bl/userService.js" },
  { key: "RA", title: "Unit — middleware/requireAuth.js" },
  { key: "EH", title: "Unit — error_handling.js" },
  { key: "LG", title: "Integration — .config/logger.js" },
  { key: "MD", title: "Integration — Mongoose models" },
  { key: "DB", title: "Integration — .config/db.js (connectDB)" },
  { key: "ST", title: "Integration — index.js start-up" },
  { key: "SU", title: "API — POST /users/signup" },
  { key: "LI", title: "API — POST /users/login" },
  { key: "RF", title: "API — POST /users/refresh" },
  { key: "LO", title: "API — POST /users/logout" },
  { key: "XC", title: "API — cross-cutting (contract, headers, CORS, 404)" },
  { key: "UJ", title: "E2E — client + server auth journeys (browser)" },
];

/** id -> { purpose, under, method, expected, divergence? } */
export const CASES = {
  // ---- US ----
  "US-01": { purpose: "The access token carries only what requireAuth reads (req.user = {id, username}).", under: "issueTokenPair via signup(); jwt real.", method: "Mock createUser -> {_id:'u1', username:'amir', email:'a@x.io'}. bcrypt.hash -> 'HASHED::pw'. Call signup({username:'amir', email:'a@x.io', password:'password123'}). jwt.decode the accessToken.", expected: "Payload keys are exactly id, username, iat, exp. id==='u1', username==='amir'. No email, no password." },
  "US-02": { purpose: "The refresh token is minimal and does not carry the username.", under: "issueTokenPair via signup().", method: "As US-01; jwt.decode the refreshToken.", expected: "Payload keys are exactly userId, iat, exp. userId==='u1'." },
  "US-03": { purpose: "Access and refresh secrets are separate (spec §10 d1) — a leaked access secret must not verify a refresh token.", under: "issueTokenPair.", method: "JWT_SECRET='test-access-secret', REFRESH_TOKEN_SECRET='test-refresh-secret'. Run signup. Verify each token under each secret.", expected: "accessToken verifies only under the access secret; refreshToken only under the refresh secret; the cross cases throw." },
  "US-04": { purpose: "Token lifetimes match spec §10 decision 1.", under: "issueTokenPair.", method: "Run signup; decode both tokens; compute exp-iat.", expected: "access exp-iat === 900 (±2s); refresh exp-iat === 604800 (±2s)." },
  "US-05": { purpose: "The TTL index gets a correct date to work from.", under: "issueTokenPair -> saveRefreshToken.", method: "Freeze time at 2026-01-15T12:00:00Z. Run signup. Inspect the saveRefreshToken argument.", expected: "Called once with { token:<string>, user:'u1', expiresAt:<Date> } where expiresAt.getTime() === Date.now() + 7*24*60*60*1000 exactly." },
  "US-06": { purpose: "The repository never receives a plain password.", under: "signup().", method: "bcrypt.hash spy -> 'HASHED::'+input. Call signup with password:'plaintextpw'. Inspect bcrypt.hash and createUser calls.", expected: "bcrypt.hash called once with ('plaintextpw', 10). createUser called once with password === 'HASHED::plaintextpw'." },
  "US-07": { purpose: "The route gets { user, accessToken, refreshToken }.", under: "signup() return value.", method: "Run signup, inspect the resolved object.", expected: "Keys exactly user, accessToken, refreshToken. user is the createUser result. Both tokens are non-empty strings." },
  "US-08": { purpose: "The service does not swallow or remap E11000 — the central handler does (spec §8, §10 d3).", under: "signup() error propagation.", method: "createUser rejects with Object.assign(new Error('E11000 dup key'), {code:11000}). Run signup.", expected: "signup rejects with the SAME error object; .code===11000 intact; saveRefreshToken never called." },
  "US-09": { purpose: "Happy-path login (spec §4 login).", under: "login().", method: "findUserByUsername -> user with password:'HASHED'. bcrypt.compare -> true. Call login('amir','rightpw').", expected: "Resolves { user, accessToken, refreshToken }; user._id==='u1'; bcrypt.compare called with ('rightpw','HASHED')." },
  "US-10": { purpose: "The response must not reveal which credential was wrong (spec §4 step 2, §8).", under: "login() failure paths.", method: "Case A: findUserByUsername -> null; login('ghost','x'). Case B: user present, bcrypt.compare -> false; login('amir','wrong').", expected: "Both reject with .status===401 and message 'Username or password is incorrect.' — byte-identical. Case A does not call bcrypt.compare. No token issued in either." },
  "US-11": { purpose: "Rotation (spec §4 refresh steps 1-6).", under: "refresh() happy path.", method: "findRefreshToken -> truthy row. Pre-sign a valid refresh token for {userId:'u1'}. findUserById -> user. deleteRefreshToken resolves. Call refresh(oldToken).", expected: "Resolves { user, accessToken, refreshToken }. deleteRefreshToken called once with oldToken. saveRefreshToken called once with a DIFFERENT token. user._id==='u1'." },
  "US-12": { purpose: "A rotated-out or pre-restart token is rejected before jwt.verify (spec §4 refresh step 1).", under: "refresh() unknown token.", method: "findRefreshToken -> null. Call refresh('whatever').", expected: "Rejects with .status===401, message 'not recognized'. findUserById / deleteRefreshToken never called." },
  "US-13": { purpose: "A tampered/expired token that is somehow in the collection still fails; rotation aborts before the delete (spec §4 refresh step 2).", under: "refresh() jwt.verify failure.", method: "findRefreshToken -> truthy row. Pass 'not.a.jwt' so real jwt.verify throws. Call refresh('not.a.jwt').", expected: "Rejects with an Error. deleteRefreshToken / saveRefreshToken never called." },
  "US-14": { purpose: "End-to-end rotation property at the unit level.", under: "refresh() called twice with the same token.", method: "First call: full happy path, deleteRefreshToken resolves. Then findRefreshToken.mockResolvedValue(null). Call refresh(old) again.", expected: "First call resolves; second call rejects with .status===401 / 'not recognized'." },
  "US-15": { purpose: "Logout invalidates the refresh token (spec §4 logout).", under: "logout().", method: "deleteRefreshToken resolves. Call logout('tok123').", expected: "deleteRefreshToken called once with 'tok123'. Resolves to undefined." },
  "US-16": { purpose: "Logout is idempotent / safe when no cookie was sent (spec §4 logout).", under: "logout(undefined).", method: "deleteRefreshToken resolves. Call logout(undefined).", expected: "Does not throw; resolves. deleteRefreshToken called once with undefined." },
  "US-17": { purpose: "The private helper stays private (spec §4 'not exported').", under: "userService module exports.", method: "require the module and inspect its keys.", expected: "Exported keys are exactly signup, login, refresh, logout. No issueTokenPair." },
  "US-18": { purpose: "Login creates a RefreshToken row (spec 04 'RefreshToken': Login creates one).", under: "login() -> issueTokenPair -> saveRefreshToken.", method: "As US-09; inspect saveRefreshToken.", expected: "Called once with { token:<string>, user:'u1', expiresAt:<Date ~7d out> }." },

  // ---- RA ----
  "RA-01": { purpose: "An unauthenticated request never reaches the route (spec §4 step 2).", under: "requireAuth with no Authorization header.", method: "req.headers = {}. Call requireAuth(req,res,next).", expected: "res.status(401), res.json({error:'Not authenticated.'}). next NOT called. req.user undefined." },
  "RA-02": { purpose: "A malformed auth scheme is rejected (spec §4 step 2).", under: "requireAuth with 'Token abc123'.", method: "authorization:'Token abc123'. Call requireAuth.", expected: "401 {error:'Not authenticated.'}. next NOT called." },
  "RA-03": { purpose: "'Bearer ' with an empty token must not verify (spec §4 step 3 body).", under: "requireAuth with 'Bearer ' (empty token).", method: "authorization:'Bearer '. Call requireAuth.", expected: "401, body { error:'Not authenticated.' } per spec §4 step 3. (Shares the code's catch string with RA-06.)" },
  "RA-04": { purpose: "The guard attaches only the two fields routes need, not the raw JWT payload (spec §4 step 4).", under: "requireAuth with a valid token.", method: "Sign {id:'u1', username:'amir'} with JWT_SECRET, 15m. authorization:'Bearer <token>'. Call requireAuth.", expected: "next called exactly once with no arg. req.user deep-equals {id:'u1', username:'amir'} — NO iat, NO exp. res.status/json not called." },
  "RA-05": { purpose: "An expired access token is rejected (spec §4 step 3).", under: "requireAuth with an expired token.", method: "Sign with { expiresIn:-10 }. authorization:'Bearer <expired>'. Call requireAuth.", expected: "res.status(401). next not called." },
  "RA-06": { purpose: "Spec 06 §4 step 3 fixes the failed-verify body as { error:'Not authenticated.' }, identical to the missing-header case.", under: "requireAuth with a wrong-secret token.", method: "jwt.sign(payload,'wrong-secret'). authorization:'Bearer <tampered>'. Call requireAuth.", expected: "Per spec: res.json({error:'Not authenticated.'}). Actual code (line 41): { error:'Invalid or expired token!' }. Status 401 and no-next are correct; only the string violates the spec.", divergence: "SPEC DIVERGENCE — message string. Fix: change requireAuth.js line 41 to { error: 'Not authenticated.' }, or amend spec 06 §4." },
  "RA-07": { purpose: "A token with a mutated signature does not pass.", under: "requireAuth with a flipped signature byte.", method: "Take a valid token, flip the last char of the signature segment. authorization:'Bearer <mutated>'. Call requireAuth.", expected: "res.status(401). next not called. req.user undefined." },
  "RA-08": { purpose: "The token is self-contained; requireAuth must not hit Mongo (spec §4 'Does not touch the database').", under: "requireAuth.js source.", method: "Read the file; list every require() specifier.", expected: "The only require is 'jsonwebtoken'. No models/, dal/, or mongoose reference." },
  "RA-09": { purpose: "Documents the exact mapping: req.user = { id: decoded.id, username: decoded.username } — two named fields, no validation.", under: "requireAuth with a token whose payload lacks username.", method: "Sign { id:'u1' } only. Call requireAuth.", expected: "next called once. req.user deep-equals { id:'u1', username: undefined }." },

  // ---- EH ----
  "EH-01": { purpose: "An async throw does not crash the process; it reaches the central handler (spec §3.1).", under: "catchAsync with a rejecting handler.", method: "const boom = new Error('kaboom'); wrapped = catchAsync(async () => { throw boom }); call wrapped(req,res,next); await a tick.", expected: "next called exactly once with boom (same reference). res.status/json never called." },
  "EH-02": { purpose: "The wrapper is transparent on the happy path.", under: "catchAsync with a resolving handler.", method: "wrapped = catchAsync(async (req,res) => res.json({ok:true})); call it; await a tick.", expected: "next not called. res.json({ok:true}) called once by the handler." },
  "EH-03": { purpose: "Logging happens once, in errorHandler only (spec §3.3, decision 2 — no double logging).", under: "catchAsync.", method: "As EH-01; inspect the logger spies after the tick.", expected: "logger.warn / error / info / http all zero calls." },
  "EH-04": { purpose: "Promise.resolve(handler(...)) also catches a sync throw inside an async handler; documents the boundary.", under: "catchAsync with a synchronously-throwing async handler.", method: "wrapped = catchAsync(async () => { JSON.parse('{') }); call it; await a tick.", expected: "next called once with a SyntaxError." },
  "EH-05": { purpose: "Duplicate-key errors become a 409 here, once, for every unique-indexed model (spec §3.2, 05 d3).", under: "errorHandler with err.code === 11000.", method: "err = Object.assign(new Error('E11000 duplicate key error ... username_1'), {code:11000}); call errorHandler(err,req,res,next).", expected: "res.status(409). res.json called once with an object whose only key is error (a string). logger.warn once; logger.error not called.", divergence: "SPEC WORDING NOTE — spec §3.2 table gives the message as '<field> already exists.'; code returns 'That username or email is already taken.'. Status + shape are correct and asserted; wording divergence recorded, not failed." },
  "EH-06": { purpose: "A deliberate error (e.g. 401 from userService.login) is passed through with its chosen message (spec §3.2 row 2, §3.3).", under: "errorHandler with err.status set.", method: "err = Object.assign(new Error('Username or password is incorrect.'), {status:401}); call errorHandler.", expected: "res.status(401), res.json({error:'Username or password is incorrect.'}). logger.warn once; logger.error not called." },
  "EH-07": { purpose: "Deliberate 4xx keep error.log clean (spec §3.3).", under: "errorHandler with a 400 err.status.", method: "err = Object.assign(new Error('bad'), {status:400}); call errorHandler.", expected: "res.status(400), res.json({error:'bad'}). logger.warn once, logger.error zero." },
  "EH-08": { purpose: "An unexpected error is a 5xx and is logged as a real problem (spec §3.2 row 3, §3.3).", under: "errorHandler with no status/code.", method: "err = new Error('connection reset by peer'); call errorHandler.", expected: "res.status(500), res.json({error:'Something went wrong.'}). logger.error once; logger.warn not called." },
  "EH-09": { purpose: "The real failure message is logged, not sent to the client (spec §3.2 row 3).", under: "errorHandler 500 branch body.", method: "err = new Error('SECRET table users missing column ssn'); call errorHandler; inspect the res.json argument.", expected: "res.json argument is exactly { error:'Something went wrong.' }. 'SECRET' does not appear in the JSON argument. logger.error's first argument DOES contain the real message." },
  "EH-10": { purpose: "The handler only ever emits the general shape; { errors:[] } is produced earlier by validators and never reaches here (spec §3.2 'Key points').", under: "errorHandler across all three branches.", method: "Run the 11000, err.status, and fallback branches; collect each res.json argument.", expected: "Each argument has exactly one own key, error, a non-empty string. No errors key anywhere." },
  "EH-11": { purpose: "No double logging (decision 2).", under: "errorHandler logging count.", method: "For each branch, sum all logger spy call counts after one errorHandler call.", expected: "Total logger calls === 1 in every branch." },

  // ---- LG ----
  "LG-01": { purpose: "The separate error log is a filter, not a redirect — errors still go to the everything-log (spec §1).", under: "logger.error line routing.", method: "chdir into a temp dir, require a fresh logger. logger.error('disk fell off', {path:'/x'}). flush. Read logs/error.log and logs/app.log.", expected: "Both files contain a line with 'disk fell off' and [ERROR]." },
  "LG-02": { purpose: "error.log stays a list of real problems (spec §3.3 rationale, §1 table).", under: "logger.warn line routing.", method: "logger.warn('recovered ok'). flush. Read both files.", expected: "app.log contains 'recovered ok' [WARN]; error.log does NOT contain 'recovered ok'." },
  "LG-03": { purpose: "The AI-call log is fed by the area==='ai' filter (spec §1, decision 1).", under: "logger.info with { area:'ai' }.", method: "logger.info('gemini call', {area:'ai', ms:42, ok:true}). flush. Read logs/ai.log.", expected: "ai.log contains a line with 'gemini call' and \"ms\":42." },
  "LG-04": { purpose: "ai.log on its own is the uncluttered AI history (spec §1).", under: "logger.info with no area.", method: "logger.info('server started'). flush. Read logs/ai.log.", expected: "ai.log does NOT contain 'server started'. (app.log does.)" },
  "LG-05": { purpose: "AI lines still also appear in logs/app.log (spec §1).", under: "logger.info with { area:'ai' } -> app.log.", method: "From LG-03's write, read app.log.", expected: "app.log contains 'gemini call'." },
  "LG-06": { purpose: "The shared line format only appends JSON when there are extra fields (logger.js printf).", under: "logger.info with empty meta.", method: "logger.info('plain message'). flush. Read the matching line from app.log.", expected: "The line contains no { / } / {} — no trailing empty-object JSON." },
  "LG-07": { purpose: "A crash is never silent (spec §1 'Crash handlers').", under: "logger.exceptions / logger.rejections handlers.", method: "require the logger; inspect the exception and rejection handler transports' filenames.", expected: "At least one exception handler transport filename ends 'exception.log'; at least one rejection handler transport filename ends 'rejection.log'." },

  // ---- MD ----
  "MD-01": { purpose: "username is required (spec 04 User).", under: "userModel validation.", method: "new User({email:'a@x.io', password:'h'}).validate().", expected: "Rejects; err.errors.username present, kind 'required'." },
  "MD-02": { purpose: "username min length 3 (spec 04 User: 3-20).", under: "userModel validation.", method: "new User({username:'ab', email:'a@x.io', password:'h'}).validate().", expected: "Rejects; err.errors.username; message mentions '3 characters'." },
  "MD-03": { purpose: "username max length 20 (spec 04 User: 3-20).", under: "userModel validation.", method: "username = 21 chars. .validate().", expected: "Rejects; err.errors.username; message mentions '20'." },
  "MD-04": { purpose: "username is trimmed (spec 04 User).", under: "userModel setter.", method: "new User({username:'  amir  ', ...}); read .username.", expected: "'amir'." },
  "MD-05": { purpose: "email must pass validator.isEmail (spec 04 User: valid email).", under: "userModel validation.", method: "new User({username:'amir', email:'not-an-email', password:'h'}).validate().", expected: "Rejects; err.errors.email; message 'Please enter a valid email address'." },
  "MD-06": { purpose: "email is lowercased (spec 04 User).", under: "userModel setter.", method: "new User({..., email:'Amir@Example.IO', ...}); read .email.", expected: "'amir@example.io'." },
  "MD-07": { purpose: "username and email are unique (spec 04 User: required, unique).", under: "users collection indexes after User.init().", method: "await User.init(); User.collection.getIndexes({full:true}).", expected: "An index on {username:1} with unique:true, and one on {email:1} with unique:true." },
  "MD-08": { purpose: "createdAt is set automatically; toJSON exposes the id virtual (spec 04 User; 05 §5).", under: "userModel default + toJSON.", method: "Construct a User; check createdAt is a Date within 5s of now. Save; call toJSON().", expected: "createdAt recent Date. toJSON().id is a string equal to _id.toString()." },
  "MD-09": { purpose: "token is required (spec 04 RefreshToken).", under: "refreshTokenModel validation.", method: "new RefreshToken({user:<oid>, expiresAt:new Date()}).validate().", expected: "Rejects; err.errors.token, kind 'required'." },
  "MD-10": { purpose: "user is a required ObjectId ref to User (spec 04 RefreshToken).", under: "refreshTokenModel validation + schema.", method: "validate() without user; validate() with user:'not-an-oid'. Inspect schema path 'user'.", expected: "First rejects on user required; second rejects on cast error. Schema path user ref === 'User'." },
  "MD-11": { purpose: "expiresAt is required (spec 04 RefreshToken).", under: "refreshTokenModel validation.", method: "new RefreshToken({token:'t', user:<oid>}).validate().", expected: "Rejects; err.errors.expiresAt, kind 'required'." },
  "MD-12": { purpose: "token is unique (spec 04 RefreshToken).", under: "refreshtokens collection indexes.", method: "await RefreshToken.init(); getIndexes({full:true}).", expected: "An index on {token:1} with unique:true." },
  "MD-13": { purpose: "MongoDB removes expired tokens on its own (spec 04 RefreshToken: 'Put a TTL index on expiresAt').", under: "refreshtokens TTL index.", method: "getIndexes({full:true}); find the index whose key is {expiresAt:1}.", expected: "That index has expireAfterSeconds === 0." },
  "MD-14": { purpose: "user is indexed (spec 04 RefreshToken: required, indexed).", under: "refreshtokens indexes.", method: "getIndexes({full:true}).", expected: "An index whose key is {user:1}." },
  "MD-15": { purpose: "amount is required (spec 04 Expense).", under: "expenseModel validation.", method: "new Expense({category:<oid>, user:<oid>}).validate().", expected: "Rejects; err.errors.amount, kind 'required'." },
  "MD-16": { purpose: "amount must be greater than 0 (spec 04 Expense; model min 0.01).", under: "expenseModel validation.", method: "new Expense({amount:0, category:<oid>, user:<oid>}).validate().", expected: "Rejects; err.errors.amount; message mentions 'greater than 0'." },
  "MD-17": { purpose: "amount cannot be negative (spec 04 Expense).", under: "expenseModel validation.", method: "amount:-5. .validate().", expected: "Rejects; err.errors.amount." },
  "MD-18": { purpose: "amount of exactly 0.01 is accepted (model min is 0.01).", under: "expenseModel validation.", method: "new Expense({amount:0.01, category:<oid>, user:<oid>}).validate().", expected: "Resolves (no error)." },
  "MD-19": { purpose: "date defaults to today; category and user are required refs (spec 04 Expense).", under: "expenseModel defaults + validation + schema.", method: "Construct a valid Expense without date -> .date is a recent Date. new Expense({amount:5}).validate() -> rejects on category and user. Inspect schema path refs.", expected: "date recent Date; both category and user error; refs are 'Category' and 'User'." },
  "MD-20": { purpose: "Every dashboard query is 'this user, this period' (spec 04 Expense: index on user + date).", under: "expenses indexes.", method: "await Expense.init(); getIndexes({full:true}).", expected: "An index whose key is exactly {user:1, date:1}." },

  // ---- DB ----
  "DB-01": { purpose: "Happy path (spec §2 step 3).", under: "connectDB() with a good URI, in a child process.", method: "fork qa/harness/db-driver.js with MONGODB_URI = the derived test URI (.../expenses_qa_test), exit 0 after 4s. Capture stdout.", expected: "Child exits 0. Output contains 'connected to MongoDB' and [INFO]. No [ERROR]." },
  "DB-02": { purpose: "A server with no database must not stay up (spec §2 step 4, decision 3).", under: "connectDB() with a bad URI, in a child process.", method: "fork the driver with MONGODB_URI='mongodb://127.0.0.1:59999/nope?serverSelectionTimeoutMS=3000'. Wait for exit.", expected: "Child exits non-zero. Output contains 'Error connecting to MongoDB' and [ERROR]." },
  "DB-03": { purpose: "Scope (spec §2 'Not this module's job').", under: "db.js module exports.", method: "require('backend/.config/db.js') in-process; inspect exports; check mongoose.modelNames() is unchanged.", expected: "Exports are exactly { connectDB } (a function). require registers no Mongoose models." },

  // ---- ST ----
  "ST-01": { purpose: "spec §1 step 1 — require('dotenv').config() is the very first line.", under: "index.js start-up + static source.", method: "Static: first executable statement is require('dotenv').config(), before any other require. Behavioural: the shared server (spawned by the harness with PORT=3100) logged its readiness line; a POST /users/login with {} returns a well-formed 400.", expected: "First statement matches require('dotenv').config(); stdout contains 'Server running on http://localhost:3100'; the empty-body login returns 400." },
  "ST-02": { purpose: "spec §1 steps 6-7 — connect, then listen.", under: "index.js source order + running server.", method: "Static: connectDB() appears before app.listen( in index.js. Behavioural: GET /users/<unknown> returns a JSON 404 (not a connection error) and stdout also shows 'connected to MongoDB'.", expected: "connectIdx < listenIdx; the 404 response has content-type application/json; 'connected to MongoDB' present." },
  "ST-03": { purpose: "spec §1 step 6 / 06 §2 step 4 — no DB => no server.", under: "a fresh index.js spawn with a broken MONGODB_URI.", method: "spawn node backend/index.js with MONGODB_URI='mongodb://127.0.0.1:59999/nope?serverSelectionTimeoutMS=3000', PORT=3101. Send no requests. Wait up to 15s.", expected: "The child exits with a non-zero code (does not stay alive). Output contains 'Error connecting to MongoDB'. (The port may briefly bind before Mongoose gives up; the pass condition is process death via connectDB's process.exit(1).)" },

  // ---- SU ----
  "SU-01": { purpose: "Valid signup succeeds (spec 03 §1: 201 Created).", under: "POST /users/signup happy path.", method: "POST a fresh makeUser() body {username:'qa_<id>', email:'qa_<id>@test.io', password:'password123'}.", expected: "HTTP 201." },
  "SU-02": { purpose: "The success body is exactly { user:{id,username,email}, accessToken } (spec 03 §1, 05 §5).", under: "signup success body shape.", method: "Parse the SU-01 response; validate against AuthSuccess.strict().", expected: "Validation passes. Top-level keys exactly user, accessToken. user keys exactly id, username, email." },
  "SU-03": { purpose: "Password never leaves the server (spec 03 §1, 05 §5).", under: "signup body — secret leak.", method: "Stringify the whole body; search for 'password', '$2a$', '$2b$', '$2y$'.", expected: "None present." },
  "SU-04": { purpose: "spec 05 §10 decision 4 — response body is {id,username,email} only.", under: "signup body — createdAt.", method: "Inspect body.user.", expected: "No createdAt key." },
  "SU-05": { purpose: "The refresh token lives only in the cookie (spec 05 §5).", under: "signup body — refreshToken.", method: "Stringify the body; search for 'refreshToken'.", expected: "Not present." },
  "SU-06": { purpose: "Cookie options per spec 05 §6.1.", under: "signup Set-Cookie for refreshToken.", method: "Read the set-cookie header from SU-01; parse the refreshToken directive's attributes.", expected: "HttpOnly; SameSite=Lax; Max-Age=604800; Path=/. NOT Secure (local http)." },
  "SU-07": { purpose: "The id is a real Mongo ObjectId and the echoed fields match the request (email lowercased).", under: "signup body.user values.", method: "From SU-01, check body.user.", expected: "id matches /^[a-f0-9]{24}$/. username === request username. email === request email lowercased." },
  "SU-08": { purpose: "spec 05 §7 (username 3-20) + 03 §0 error shape.", under: "signup with username 'ab'.", method: "POST with username:'ab', valid email, valid password.", expected: "HTTP 400. Body matches { errors:[{field,message}] }. At least one entry field==='username'. No error key. No user/accessToken." },
  "SU-09": { purpose: "spec 05 §7 (valid email).", under: "signup with email 'nope'.", method: "POST with valid username, email:'nope', valid password.", expected: "HTTP 400; an entry field==='email'." },
  "SU-10": { purpose: "spec 05 §7 (password >= 8).", under: "signup with password 'short'.", method: "POST with valid username/email, password:'short'.", expected: "HTTP 400; an entry field==='password'." },
  "SU-11": { purpose: "spec 03 §0 — field must be username/email/password so the client maps it to the right input.", under: "signup with all three fields invalid.", method: "POST with username:'ab', email:'nope', password:'x'.", expected: "HTTP 400; every errors[].field is in {username,email,password}." },
  "SU-12": { purpose: "spec 05 §8 — normal path is the async validator (400 on the field); a race that slips past becomes a 409 (err.code===11000).", under: "signup with a duplicate username.", method: "Sign up a user, then POST /users/signup again with the SAME username (fresh email).", expected: "HTTP 400 with an errors[] entry field==='username' OR HTTP 409 with { error:<string> }. Either way: no password in the body; one of the two agreed shapes. (400 is expected with the async validator present; 409 is accepted as spec-compliant.)" },

  // ---- RF ----
  "RF-01": { purpose: "The normal 'nobody is logged in' case on start-up (spec 05 §6 step 1).", under: "POST /users/refresh with no cookie.", method: "POST /users/refresh with no Cookie header.", expected: "HTTP 401. Body matches { error:<string> } (GeneralError.strict())." },
  "RF-02": { purpose: "spec 06 §3.3 / 05 §8 — this 401 is answered in the route, not the central handler, and must not be logged as an error.", under: "backend/logs/error.log after a no-cookie /refresh.", method: "Record error.log byte length. Send the RF-01 request. Wait 300ms. Re-read the length; if it grew, check the appended text.", expected: "error.log did not grow, OR the appended text mentions neither /users/refresh nor [ERROR]." },
  "RF-03": { purpose: "spec 03 §1 / 05 §6 — a valid refresh returns user + a new access token.", under: "POST /users/refresh with a valid cookie.", method: "signupAndGetCookie(), then POST /users/refresh with Cookie: refreshToken=<value>.", expected: "HTTP 200. Body matches AuthSuccess.strict() — user is {id,username,email} + accessToken. No password/hash/'refreshToken' string in the body." },
  "RF-04": { purpose: "The core rotation property — a new refresh cookie is issued (spec 05 §4, 04 'RefreshToken').", under: "refresh Set-Cookie.", method: "From RF-03, read set-cookie.", expected: "A refreshToken cookie is set; its value differs from the one sent in. Same attributes (HttpOnly, SameSite=Lax, Max-Age=604800, Path=/)." },
  "RF-05": { purpose: "The previous refresh token stops working after one successful rotation (spec 05 §4 steps 3-4).", under: "reusing an old refresh cookie.", method: "signupAndGetCookie() -> C1. POST /refresh with C1 -> 200, yields C2. POST /refresh AGAIN with C1.", expected: "The second call with C1 returns HTTP 401 and clears the cookie. C2 still works (POST /refresh with C2 -> 200)." },
  "RF-06": { purpose: "spec 05 §6 /refresh step 5 — a tampered token is rejected and the cookie cleared.", under: "POST /users/refresh with a mutated JWT.", method: "signupAndGetCookie(), mutate the last char of the JWT, POST /refresh with the mutated cookie.", expected: "HTTP 401, body { error:<string> }. set-cookie clears refreshToken." },
  "RF-07": { purpose: "Rotation deletes the old row and inserts one new row (spec 04 'RefreshToken', 05 §4).", under: "refreshtokens collection count across a rotation.", method: "With a QA mongo connection: signupAndGetCookie(); record count N. POST /refresh once. Wait 200ms. Re-count -> M.", expected: "M === N (one deleted, one inserted). Exactly one row exists for this user after the rotation." },
  "RF-08": { purpose: "Refresh returns the correct user (spec 03 §1 — user + token).", under: "refresh body.user.", method: "Sign up user U (known username/email), get its cookie, POST /refresh.", expected: "body.user.username === U.username; body.user.email === U.email lowercased; body.user.id is a 24-hex string." },
  "RF-09": { purpose: "A token never issued by this server (not in the collection) is rejected at step 1 of userService.refresh (spec 05 §4).", under: "POST /users/refresh with a self-signed unknown token.", method: "Sign a valid JWT with REFRESH_TOKEN_SECRET for {userId:<random ObjectId>} WITHOUT saving a row; send it as the cookie.", expected: "HTTP 401, body { error:<string> }, cookie cleared." },

  // ---- LO ----
  "LO-01": { purpose: "spec 03 §1 / 05 §6 /logout — 204 with no body.", under: "POST /users/logout with a valid cookie.", method: "signupAndGetCookie(), then POST /users/logout with Cookie: refreshToken=<value>.", expected: "HTTP 204. Response body is empty ('')." },
  "LO-02": { purpose: "The cookie must actually be cleared server-side (spec 03 §1).", under: "logout Set-Cookie.", method: "Read set-cookie from LO-01.", expected: "A refreshToken directive that expires/empties it (empty value, or Expires in the past, or Max-Age=0)." },
  "LO-03": { purpose: "Logout really invalidates the token (spec 05 §6 /logout, 04 'RefreshToken': Logout deletes it).", under: "using an old cookie on /refresh after logout.", method: "signupAndGetCookie() -> C1. POST /logout with C1. Then POST /users/refresh with C1.", expected: "The /refresh call returns HTTP 401." },
  "LO-04": { purpose: "spec 05 §6 /logout — safe to call when nobody is logged in.", under: "POST /users/logout with no cookie.", method: "POST /users/logout with no Cookie header.", expected: "HTTP 204, empty body. No error." },
  "LO-05": { purpose: "userService.logout is idempotent (spec 05 §4 logout).", under: "POST /users/logout twice with the same cookie.", method: "signupAndGetCookie() -> C1. POST /logout with C1, then POST /logout with C1 again.", expected: "Both calls return HTTP 204. Neither throws a 500." },

  // ---- XC ----
  "XC-01": { purpose: "spec 03 §0 — the client understands only { error:string } or { errors:[{field,message}] }.", under: "error bodies from login(400/401), signup(400), refresh(401), 404.", method: "Collect those five error responses; parse JSON of each.", expected: "Each body has EITHER exactly key error (string) OR exactly key errors (array of {field,message}). No body has both or any third top-level key." },
  "XC-02": { purpose: "spec 03 §0 — the client puts the message under the input named by field.", under: "signup with username:'ab', email:'bad', password:'x'.", method: "POST that body; parse the 400.", expected: "HTTP 400; every errors[].field is one of 'username', 'email', 'password'." },
  "XC-03": { purpose: "spec 01 §2, 03 §1, 05 §5 — password never leaves the server.", under: "success bodies of signup(201), login(200), refresh(200).", method: "Capture the three success bodies; stringify each; search for 'password', '$2a$', '$2b$', '$2y$'.", expected: "None present in any of the three." },
  "XC-04": { purpose: "spec 05 §5 — refreshToken only in Set-Cookie, never in a JSON body.", under: "signup + login bodies and their Set-Cookie.", method: "Stringify each body; search for 'refreshToken'. Confirm set-cookie carries it.", expected: "'refreshToken' absent from every body; present in set-cookie on signup/login." },
  "XC-05": { purpose: "spec 07 §2 #1 — helmet is mounted so it covers every response.", under: "response headers on a 201 signup.", method: "POST a fresh signup; inspect response headers.", expected: "x-content-type-options: nosniff; x-dns-prefetch-control present; content-security-policy present; x-powered-by absent." },
  "XC-06": { purpose: "spec 07 §2 #1 — 'including errors'.", under: "response headers on a 404.", method: "GET /nope; inspect headers.", expected: "x-content-type-options: nosniff present; x-powered-by absent." },
  "XC-07": { purpose: "spec 03 §0 / 07 §2 #2 — cors({ origin:'http://localhost:5173', credentials:true }), not *.", under: "CORS response headers for the client origin.", method: "POST /users/login with request header Origin: http://localhost:5173.", expected: "access-control-allow-origin: http://localhost:5173 (exact); access-control-allow-credentials: true." },
  "XC-08": { purpose: "The browser preflight must succeed for the client origin.", under: "OPTIONS /users/login.", method: "OPTIONS /users/login with Origin: http://localhost:5173 and Access-Control-Request-Method: POST.", expected: "A 2xx/204 status; access-control-allow-origin: http://localhost:5173; access-control-allow-credentials: true." },
  "XC-09": { purpose: "spec 07 §27 — CORS locked to one origin.", under: "CORS with a foreign origin.", method: "POST /users/login with Origin: http://evil.example.", expected: "The response does NOT carry access-control-allow-origin: http://evil.example." },
  "XC-10": { purpose: "spec 07 §4 #1 — an unmatched path returns 404 with the general error shape.", under: "GET /this/does/not/exist.", method: "GET a random unmatched path.", expected: "HTTP 404; body has exactly one key error (a string)." },
  "XC-11": { purpose: "spec 07 §4 #1 fixes the 404 body as { \"error\": \"Not found.\" }.", under: "GET an unmatched path — body message.", method: "GET a random unmatched path; read body.error.", expected: "Per spec: body.error === 'Not found.'. Actual code (index.js line 57): { error: 'Not Found' } (capital F, no period).", divergence: "SPEC DIVERGENCE — 404 message string. Status (404) and shape ({error}) are correct. Fix: change index.js line 57 to 'Not found.', or amend spec 07 §4. Low severity (client shows a generic message)." },
  "XC-12": { purpose: "spec 07 §2 #3-#4 — express.json before the routers, cookie-parser before /users/refresh.", under: "JSON body parsing + cookie parsing wiring.", method: "(a) POST /users/login with a JSON body -> the server reads req.body. (b) POST /users/refresh with Cookie: refreshToken=x -> the server reads req.cookies.", expected: "(a) 400 with the errors shape. (b) 401 with the error shape — never a 500/TypeError." },
  "XC-13": { purpose: "spec 07 §2 lists helmet() as middleware #1; the code mounts compression() first (line 30) and helmet() second (line 31).", under: "index.js app.use order + helmet coverage.", method: "Static: record the order of app.use( lines. Behavioural: confirm helmet headers on a 404.", expected: "helmet headers present on all responses (PASS). The ordering difference is recorded as a design note.", divergence: "DESIGN NOTE — compression() is mounted before helmet(); spec 07 §2 says helmet is #1. compression() sends no response of its own, so nothing is left un-helmeted. Not a functional failure. Fix: reorder in index.js, or note the exception in spec 07 §2." },
  "XC-14": { purpose: "spec 07 §2 #6 — a loose blanket limiter distinct from the strict /users/login one.", under: "the global rate limiter config + light behaviour.", method: "Static: index.js constructs rateLimit({ windowMs:15*60*1000, max:300, ... }) before the routers. Behavioural: send 15 rapid GET / requests.", expected: "Static config found with max:300; the 15 requests all return a non-429 status." },

  // ---- LI ----
  "LI-01": { purpose: "Valid credentials log in (spec 03 §1: 200).", under: "POST /users/login happy path.", method: "beforeAll restarts the server (clean rate limiter) and signs up a known user. POST /users/login with that user's {username, password}.", expected: "HTTP 200." },
  "LI-02": { purpose: "Login's success body equals signup's shape (spec 05 §2).", under: "login success body.", method: "Validate the LI-01 body against AuthSuccess.strict().", expected: "Passes; keys exactly user ({id,username,email}) + accessToken." },
  "LI-03": { purpose: "Login sets a fresh HttpOnly refresh cookie (spec 05 §6.1).", under: "login Set-Cookie.", method: "Read set-cookie from a successful login.", expected: "refreshToken cookie with HttpOnly, SameSite=Lax, Max-Age=604800, Path=/." },
  "LI-04": { purpose: "spec 03 §1 / 05 §5 — no secret in the body.", under: "login body — secret leak.", method: "Stringify the LI-01 body; search for 'password', '$2a$'/'$2b$'/'$2y$', 'refreshToken'.", expected: "None present." },
  "LI-05": { purpose: "spec 05 §7 — username present on /login.", under: "POST /users/login with only { password }.", method: "POST { password:'password123' } only.", expected: "HTTP 400; body matches ValidationError; an entry field==='username'; no error key." },
  "LI-06": { purpose: "spec 05 §7 — password present on /login.", under: "POST /users/login with only { username }.", method: "POST { username:'whoever' } only.", expected: "HTTP 400; an entry field==='password'." },
  "LI-07": { purpose: "spec 03 §1 / 05 §4/§8 — the response must not reveal which credential was wrong.", under: "wrong password vs unknown username.", method: "Case A: known username + wrong password. Case B: unknown username + any password. Compare status and body.", expected: "Both HTTP 401. Both bodies are exactly { error:'Username or password is incorrect.' } and deep-equal to each other. Neither sets a refreshToken cookie." },
  "LI-08": { purpose: "spec 03 §1 'Rate-limit this route more strictly'; 05 §6 (5 / 15 min).", under: "the 6th /users/login attempt in the window.", method: "restartServer() for a clean limiter; sign up a fresh user; send 5 failing POST /users/login (wrong password), then a 6th.", expected: "Attempts 1-5 return 401. Attempt 6 returns 429 with a { error:<string> } body." },
  "LI-09": { purpose: "A 429 from the login limiter uses the general error shape (spec 03 §0).", under: "the limiter's 429 body.", method: "With the limiter still tripped from LI-08, POST /users/login once more.", expected: "HTTP 429; body validates against GeneralError.strict() — exactly one key error, a string. No errors array." },
  "LI-10": { purpose: "FINDING F-1 (not a spec assertion): two logins by the same user within one wall-clock second — or a signup immediately followed by a login — make issueTokenPair sign an IDENTICAL refresh-token JWT (payload is just { userId }, jwt `iat` is second-resolution), which collides on the RefreshToken.token unique index; errorHandler maps the E11000 to a 409. A user who double-submits the login form gets a 409.", under: "POST /users/login twice in quick succession for one user.", method: "makeUser(); signup(u); POST /users/login twice back-to-back with the same credentials.", expected: "At least one of the two responses is HTTP 409, and that 409 body is the agreed { error:<string> } shape. Test PASSES by confirming the current behaviour so the finding is visible; the fix is a jti/nonce in the refresh payload (or a documented spec note).", divergence: "FINDING F-1 — same-second re-login / signup-then-login collides on RefreshToken.token unique index -> 409. Not covered by any spec assertion; a real UX bug (double-click login). Fix: add a random jti to the refresh-token payload in issueTokenPair so two tokens are never byte-identical, OR document the constraint in spec 05 §4." },

  // ---- UJ (e2e, real browser + real server) ----
  "UJ-01": { purpose: "Proves the cookie/token wiring end to end -- the access token lives only in memory, a reload loses it but the refreshToken cookie silently restores the session, and logout actually ends the session server-side (not just a client redirect).", under: "SignupPage -> POST /users/signup; App's mount-time restoreSession() -> POST /users/refresh; NavBar logged-in state and logout -> POST /users/logout.", method: "makeUser(); fill and submit the signup form; wait for /home; assert NavBar shows the username and no Log-in link; dump window.localStorage and assert no key/value contains 'token'; reload the page; assert still on /home, still logged in; click Log out; assert redirected to /login; navigate straight to /home again.", expected: "Signup lands on /home (not an error). localStorage never contains a token. After reload, still on /home with the username visible (proves restoreSession() used the cookie). After logout, /login is shown, and a direct visit to /home bounces back to /login (proves the server-side session is actually gone, not just the client state)." },
  "UJ-02": { purpose: "Mirrors LI-07 at the browser layer: the UI must render the one generic message, not something more specific, and a failed attempt must not block a legitimate retry.", under: "LoginPage -> POST /users/login; the role=alert error banner; retry with correct credentials.", method: "signup() a user directly via the API; go to /login; submit the known username with a wrong password; read the role=alert banner text; clear and refill the password with the correct one; submit again.", expected: "The banner text is exactly 'Username or password is incorrect.' -- the same generic sentence for any wrong credential. The second, correct submission lands on /home -- the earlier failure left no stuck state (form, store, or rate limiter) blocking it." },
};
